tasks_list=(
    # 'miniwob.ascending-numbers'
    # 'miniwob.bisect-angle'
    # 'miniwob.book-flight'
    # 'miniwob.book-flight-nodelay'
    # 'miniwob.buy-ticket'
    # 'miniwob.choose-date'
    # 'miniwob.choose-date-easy'
    # 'miniwob.choose-date-medium'
    # 'miniwob.choose-date-nodelay'
    # 'miniwob.choose-list'
    # 'miniwob.circle-center'
    # 'miniwob.click-button'
    # 'miniwob.click-button-sequence'
    # 'miniwob.click-checkboxes'
    # 'miniwob.click-checkboxes-large'
    # 'miniwob.click-checkboxes-soft'
    # 'miniwob.click-checkboxes-transfer'
    # 'miniwob.click-collapsible'
    # 'miniwob.click-collapsible-2'
    # 'miniwob.click-collapsible-2-nodelay'
    # 'miniwob.click-collapsible-nodelay'
    # 'miniwob.click-color'
    # 'miniwob.click-dialog'
    # 'miniwob.click-dialog-2'
    # 'miniwob.click-link'
    # 'miniwob.click-menu'
    # 'miniwob.click-menu-2'
    # 'miniwob.click-option'
    # 'miniwob.click-pie'
    # 'miniwob.click-pie-nodelay'
    # 'miniwob.click-scroll-list'
    # 'miniwob.click-shades'
    # 'miniwob.click-shape'
    # 'miniwob.click-tab'
    # 'miniwob.click-tab-2'
    # 'miniwob.click-tab-2-easy'
    # 'miniwob.click-tab-2-hard'
    # 'miniwob.click-tab-2-medium'
    # 'miniwob.click-test'
    # 'miniwob.click-test-2'
    # 'miniwob.click-test-transfer'
    # 'miniwob.click-widget'
    # 'miniwob.copy-paste'
    # 'miniwob.copy-paste-2'
    # 'miniwob.count-shape'
    # 'miniwob.count-sides'
    # 'miniwob.daily-calendar'
    # 'miniwob.drag-box'
    # 'miniwob.drag-circle'
    # 'miniwob.drag-cube'
    # 'miniwob.drag-items'
    # 'miniwob.drag-items-grid'
    # 'miniwob.drag-shapes'
    # 'miniwob.drag-shapes-2'
    # 'miniwob.drag-single-shape'
    # 'miniwob.drag-sort-numbers'
    # 'miniwob.draw-circle'
    # 'miniwob.draw-line'
    # 'miniwob.email-inbox'
    # 'miniwob.email-inbox-delete'
    'miniwob.email-inbox-forward'
    'miniwob.email-inbox-forward-nl'
    'miniwob.email-inbox-forward-nl-turk'
    'miniwob.email-inbox-important'
    'miniwob.email-inbox-nl-turk'
    'miniwob.email-inbox-noscroll'
    'miniwob.email-inbox-reply'
    'miniwob.email-inbox-star-reply'
    'miniwob.enter-date'
    'miniwob.enter-password'
    'miniwob.enter-text'
    'miniwob.enter-text-2'
    'miniwob.enter-text-dynamic'
    'miniwob.enter-time'
    'miniwob.find-greatest'
    'miniwob.find-midpoint'
    'miniwob.find-word'
    'miniwob.focus-text'
    'miniwob.focus-text-2'
    'miniwob.form-sequence'
    'miniwob.form-sequence-2'
    'miniwob.form-sequence-3'
    'miniwob.generate-number'
    'miniwob.grid-coordinate'
    'miniwob.guess-number'
    'miniwob.highlight-text'
    'miniwob.highlight-text-2'
    'miniwob.hot-cold'
    'miniwob.identify-shape'
    'miniwob.login-user'
    'miniwob.login-user-popup'
    'miniwob.multi-layouts'
    'miniwob.multi-orderings'
    'miniwob.navigate-tree'
    'miniwob.number-checkboxes'
    'miniwob.odd-or-even'
    'miniwob.order-food'
    'miniwob.phone-book'
    'miniwob.read-table'
    'miniwob.read-table-2'
    'miniwob.resize-textarea'
    'miniwob.right-angle'
    'miniwob.scroll-text'
    'miniwob.scroll-text-2'
    'miniwob.search-engine'
    'miniwob.sign-agreement'
    'miniwob.simple-algebra'
    'miniwob.simple-arithmetic'
    'miniwob.social-media'
    'miniwob.social-media-all'
    'miniwob.social-media-some'
    'miniwob.stock-market'
    'miniwob.terminal'
    'miniwob.text-editor'
    'miniwob.text-transform'
    'miniwob.tic-tac-toe'
    'miniwob.unicode-test'
    'miniwob.use-autocomplete'
    'miniwob.use-autocomplete-nodelay'
    'miniwob.use-colorwheel'
    'miniwob.use-colorwheel-2'
    'miniwob.use-slider'
    'miniwob.use-slider-2'
    'miniwob.use-spinner'
    'miniwob.visual-addition'
)

model_name="azure/gpt-4-vision-preview"

for task in "${tasks_list[@]}";
do
  python demo_agent/run_demo.py --headless True --use_self_consistency True --multi_actions False --temperature 0.7 --task_name "$task" --model_name "$model_name" --demo_mode False --slow_mo 0 --output_dir "results/miniwob_self_consistency_t_07"
done